- name: "Deploy wordpress stack"
  docker_service:
    state: present
    project_src: /tmp/{{ project_name }}

- name: "Repairing permissions"
  shell: |
      docker exec {{ project_name }}_wordpress_1 bash -c "\
        chown www-data:www-data -R /var/www/html ; \
        find /var/www/html -type d -exec chmod 755 {} ;  \
        find /var/www/html -type f -exec chmod 644 {} ; \
        chmod 600 /var/www/html/wp-config.php "

