- name: "Install ipset and iptables-persistent"
  apt:
    name: "{{ item }}"
  with_items:
    - ipset
    - iptables-persistent

- name: "Are you sure you want to proceed?"
  pause:
    prompt: |
      "You are about to create a minimal persistent set of iptables rules to prevent machines       outside of cloudflare IP range from connecting to you. Those rules will be written to

      /etc/iptables/rules.v4

      if you already have rules in there, now is the time to make a back up. Alternatively
      you can restart the present playbook without the firewall tag"

- name: "Create ipset from online list and make it persistent"
  shell: | 
    ipset create cloudflare hash:net
    for x in $(curl https://www.cloudflare.com/ips-v4); do ipset add cloudflare $x; done
    ipset save > /etc/ipset.conf

- name: "Create cloudflare chain"
  command: |
    iptables -N CloudflareChain;
    iptables -A CloudflareChain -m set --match-set cloudflare src -j RETURN;
    iptables -A CloudflareChain -j DROP;

- name: "Prevent access to port 80 and 443 from outside cloudflare"
  command: |
    iptables -A INPUT -i eth0 -p tcp -m tcp --dport 80 -m state --state NEW,ESTABLISHED -j CloudflareChain;
    iptables -A INPUT -i eth0 -p tcp -m tcp --dport 443 -m state --state NEW,ESTABLISHED -j CloudflareChain

- name: "Save iptables rules"
  command: iptables-save > /etc/iptables/rules.v4
