- name: "Create proxy_net if it does not exist"
  become: True
  tags:
    - wp_deploy
    - wp_setup
  docker_network:
    name: proxy_net

- include: create_volumes.yml
  become: True
  tags:
    - wp_volumes_setup
    - wp_setup

- include: setup.yml
  become: True
  tags: wp_setup

- include: backup.yml
  become: True
  tags: wp_all_backup

- name: "Create docker-compose folder"
  tags:
   - wp_destroy
   - wp_deploy
   - wp_restore
  file:
    name: /tmp/{{ project_name }}
    state: directory

- name: "Write docker-compose"
  tags: 
    - wp_destroy
    - wp_deploy
    - wp_restore
  template:
    src: docker-compose.j2
    dest: /tmp/{{ project_name }}/docker-compose.yml

- include: restore.yml
  become: True
  tags: wp_all_restore

- name: "Allow docker containers to communicate with the outside"
  become: True
  tags:
   - wp_deploy
   - wp_restore
  command: iptables -t nat -A POSTROUTING -s 172.16.0.0/12 ! -d 172.16.0.0/12 -j MASQUERADE

- include: deploy.yml
  become: True
  tags:
    - wp_deploy
    - wp_restore

- include: destroy.yml
  become: True
  tags: wp_destroy

- name: "Remove docker-compose folder"
  become: True
  tags:
    - wp_deploy
    - wp_destroy
    - wp_restore
  file:
    name: /tmp/{{ project_name }}
    state: absent

- debug:
    msg: The deed is done.
  tags: wp_destroy
